ego_scan_topic: /scan
ego_odom_topic: /odom
opp_odom_topic: /opp_odom
ego_drive_topic: /drive

lap_count_topic: /lap_count
lap_time_topic: /lap_time
collision_topic: /collision

race_info_topic: /race_info

# Fixed vals DO NOT CHANGE
scan_fov: 4.7
scan_beams: 1080
scan_distance_to_base_link: 0.275

map_path: /f1tenth_gym/maps/skirk.yaml
map_img_ext: .png
executable_dir: /f1tenth_gym/build/

waypoints_path: /f1tenth_gym_ros/maps/skirk.csv

# Racecar parameters (extracted from gym_bridge.py)
wheelbase: 0.3302
mass: 3.74
l_r: 0.17145
I_z: 0.04712
mu: 0.523
h_cg: 0.074
cs_f: 4.718
cs_r: 5.4562
